project_id = "uiusztanyjwmccdabtvs"

[functions.auction-engine]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false