import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Badge } from '@/components/ui/badge';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu';
import { Loader2, MoreVertical, KeyRound, CheckCircle2, StickyNote } from 'lucide-react';
import { format, parseISO } from 'date-fns';
import { toast } from 'sonner';

export default function AdminOrders() {
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);

  function reload() {
    setLoading(true);
    supabase
      .from('orders')
      .select('id, amount, status, pickup_status, pickup_code, admin_notes, created_at, lot:lots(title), buyer:profiles!orders_buyer_id_fkey(email, full_name)')
      .order('created_at', { ascending: false })
      .limit(500)
      .then(({ data }) => { setRows(data ?? []); setLoading(false); });
  }

  useEffect(() => {
    reload();
  }, []);

  async function regenerateCode(orderId: string) {
    const note = window.prompt('Reason for regenerating pickup code (added to admin notes):', 'Pickup code regenerated by admin');
    if (note === null) return;
    setBusyId(orderId);
    const { data, error } = await supabase.rpc('admin_regenerate_pickup_code', { _order_id: orderId, _note: note });
    setBusyId(null);
    if (error) return toast.error(error.message);
    toast.success(`New pickup code: ${data}`);
    reload();
  }

  async function forceComplete(orderId: string) {
    const note = window.prompt('Reason for force-completing this order:', 'Manually marked complete by admin');
    if (note === null) return;
    if (!window.confirm('Force-complete this order? This marks it collected for both parties.')) return;
    setBusyId(orderId);
    const { error } = await supabase.rpc('admin_force_complete_order', { _order_id: orderId, _note: note });
    setBusyId(null);
    if (error) return toast.error(error.message);
    toast.success('Order marked complete');
    reload();
  }

  async function addNote(orderId: string) {
    const note = window.prompt('Add admin note to this order:');
    if (!note) return;
    setBusyId(orderId);
    const { error } = await supabase.rpc('admin_add_order_note', { _order_id: orderId, _note: note });
    setBusyId(null);
    if (error) return toast.error(error.message);
    toast.success('Note added');
    reload();
  }

  if (loading) return <div className="flex items-center justify-center py-16"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;

  return (
    <div className="p-6 space-y-4">
      <div>
        <h1 className="text-2xl font-bold">Orders</h1>
        <p className="text-muted-foreground">{rows.length} orders total</p>
      </div>
      <div className="border rounded-md overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Lot</TableHead>
              <TableHead>Buyer</TableHead>
              <TableHead>Amount</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Pickup</TableHead>
              <TableHead>Code</TableHead>
              <TableHead>Date</TableHead>
              <TableHead></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map(o => (
              <TableRow key={o.id}>
                <TableCell className="font-medium">{o.lot?.title ?? '—'}</TableCell>
                <TableCell>{o.buyer?.full_name ?? o.buyer?.email ?? '—'}</TableCell>
                <TableCell>${Number(o.amount).toLocaleString()}</TableCell>
                <TableCell><Badge variant="muted">{o.status}</Badge></TableCell>
                <TableCell><Badge variant="muted">{o.pickup_status ?? '—'}</Badge></TableCell>
                <TableCell className="font-mono text-xs">
                  {o.pickup_code
                    ? <span>{o.pickup_code}</span>
                    : <Badge variant="destructive">missing</Badge>}
                </TableCell>
                <TableCell className="text-muted-foreground">{format(parseISO(o.created_at), 'MMM d, yyyy')}</TableCell>
                <TableCell className="text-right">
                  <div className="flex items-center gap-1 justify-end">
                    <Link to={`/app/orders/${o.id}`} className="text-primary hover:underline text-sm">Open</Link>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button size="icon" variant="ghost" disabled={busyId === o.id}>
                          <MoreVertical className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={() => regenerateCode(o.id)}>
                          <KeyRound className="h-4 w-4 mr-2" /> Regenerate pickup code
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => forceComplete(o.id)} disabled={o.status === 'collected' || o.status === 'cancelled'}>
                          <CheckCircle2 className="h-4 w-4 mr-2" /> Force-complete order
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem onClick={() => addNote(o.id)}>
                          <StickyNote className="h-4 w-4 mr-2" /> Add admin note
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}